# Generated by Django 3.1.4 on 2020-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
