# Generated by Django 3.1.4 on 2020-12-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201209_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
