# Generated by Django 3.1.4 on 2020-12-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201209_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='20eea097-5710-451b-80f8-0024d63a4c59', max_length=100, unique=True),
        ),
    ]
