# Generated by Django 3.1.4 on 2020-12-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201211_1046'),
        ('post', '0012_auto_20201209_1238'),
    ]

    operations = [
    ]
