# Generated by Django 3.1.4 on 2020-12-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_merge_20201212_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
