# Generated by Django 3.1.4 on 2020-12-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_section',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
