# Generated by Django 3.1.4 on 2020-12-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_is_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='container_class',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='container_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
