# Generated by Django 3.1.4 on 2020-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20201228_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order_key',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
