# Generated by Django 3.1.4 on 2021-01-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_post_order_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wordiness',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
