# Generated by Django 3.1.4 on 2021-01-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_footeritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footeritem',
            name='href',
            field=models.CharField(max_length=1000),
        ),
    ]
