# Generated by Django 3.1.4 on 2021-01-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='ip',
            field=models.CharField(default=None, max_length=39),
            preserve_default=False,
        ),
    ]
