# Generated by Django 3.1.4 on 2021-11-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20210121_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
