# Generated by Django 3.1.4 on 2021-11-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_post_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
