# Generated by Django 3.1.4 on 2022-06-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_skill_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='price_unit',
            field=models.CharField(blank=True, default='per hour', max_length=100),
        ),
    ]
