# Generated by Django 3.1.4 on 2022-06-14 13:32

from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_skill_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='price_unit',
            field=post.models.NoStripCharField(blank=True, default='per hour', max_length=100),
        ),
    ]
