# Generated by Django 3.1.4 on 2022-06-19 01:42

from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_auto_20220614_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='recurring_price',
            field=post.models.PriceField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='recurring_price_unit',
            field=post.models.NoStripCharField(blank=True, default='per month', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='revision_price',
            field=post.models.PriceField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='revision_price_unit',
            field=post.models.NoStripCharField(blank=True, default='per revision', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='price',
            field=post.models.PriceField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
