# Generated by Django 3.1.4 on 2022-06-19 02:05

from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_auto_20220618_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='revision_price_unit',
            field=post.models.NoStripCharField(blank=True, default='per tweak', max_length=100),
        ),
    ]
