# Generated by Django 3.1.4 on 2022-06-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0033_auto_20220619_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_consultation',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
