# Generated by Django 3.1.4 on 2021-01-12 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210112_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
    ]
