# Generated by Django 3.1.4 on 2021-01-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_message_contact_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
